services:
  - docker:dind

stages:
  - build

variables:
  IMAGE_NAME_BASE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}
  IMAGE_TAG: v${CI_COMMIT_SHORT_SHA}-${CI_COMMIT_REF_SLUG}

build-image:
  stage: build
  only:
    refs:
      - main
  image:
    name: docker:latest
    entrypoint: [""]

  before_script:
    - echo "Building ${IMAGE_NAME_BASE}:${IMAGE_TAG}"
    - echo -n ${IMAGE_TAG} > version

  script:
    - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" ${CI_REGISTRY}
    - docker build --pull -t ${IMAGE_NAME_BASE}:${IMAGE_TAG} .
    - docker push ${IMAGE_NAME_BASE}:${IMAGE_TAG}